parameters:
#    site_site2.example.class: Site\Site2Bundle\Example

services:
#    site_site2.example:
#        class: %site_site2.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
